package b4a.example.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_match___copy__2_{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3d);
views.get("button22").vw.setTop((int)((12d / 100 * height) - (views.get("button22").vw.getHeight())));
views.get("button22").vw.setLeft((int)((2d / 100 * height)));
views.get("imageview1").vw.setTop((int)((33d / 100 * height) - (views.get("imageview1").vw.getHeight())));
views.get("imageview1").vw.setLeft((int)((8d / 100 * height)));
views.get("label1").vw.setTop((int)((32d / 100 * height) - (views.get("label1").vw.getHeight())));
views.get("label1").vw.setLeft((int)((15d / 100 * height)));
views.get("button1").vw.setTop((int)((35d / 100 * height) - (views.get("button1").vw.getHeight())));
views.get("button1").vw.setLeft((int)((6d / 100 * height)));
views.get("imageview2").vw.setTop((int)((33d / 100 * height) - (views.get("imageview2").vw.getHeight())));
views.get("imageview2").vw.setLeft((int)((30d / 100 * height)));
views.get("label2").vw.setTop((int)((32d / 100 * height) - (views.get("label2").vw.getHeight())));
views.get("label2").vw.setLeft((int)((37d / 100 * height)));
views.get("button2").vw.setTop((int)((35d / 100 * height) - (views.get("button2").vw.getHeight())));
views.get("button2").vw.setLeft((int)((28d / 100 * height)));
views.get("imageview3").vw.setTop((int)((33d / 100 * height) - (views.get("imageview3").vw.getHeight())));
views.get("imageview3").vw.setLeft((int)((52d / 100 * height)));
views.get("label3").vw.setTop((int)((32d / 100 * height) - (views.get("label3").vw.getHeight())));
views.get("label3").vw.setLeft((int)((59d / 100 * height)));
views.get("button3").vw.setTop((int)((35d / 100 * height) - (views.get("button3").vw.getHeight())));
views.get("button3").vw.setLeft((int)((50d / 100 * height)));
views.get("imageview4").vw.setTop((int)((33.5d / 100 * height) - (views.get("imageview4").vw.getHeight())));
views.get("imageview4").vw.setLeft((int)((74d / 100 * height)));
views.get("label4").vw.setTop((int)((32d / 100 * height) - (views.get("label4").vw.getHeight())));
views.get("label4").vw.setLeft((int)((81d / 100 * height)));
views.get("button4").vw.setTop((int)((35d / 100 * height) - (views.get("button4").vw.getHeight())));
views.get("button4").vw.setLeft((int)((72d / 100 * height)));
views.get("imageview13").vw.setTop((int)((33d / 100 * height) - (views.get("imageview13").vw.getHeight())));
views.get("imageview13").vw.setLeft((int)((96d / 100 * height)));
views.get("label13").vw.setTop((int)((32d / 100 * height) - (views.get("label13").vw.getHeight())));
views.get("label13").vw.setLeft((int)((103d / 100 * height)));
views.get("button13").vw.setTop((int)((35d / 100 * height) - (views.get("button13").vw.getHeight())));
views.get("button13").vw.setLeft((int)((94d / 100 * height)));
views.get("imageview14").vw.setTop((int)((33d / 100 * height) - (views.get("imageview14").vw.getHeight())));
views.get("imageview14").vw.setLeft((int)((118d / 100 * height)));
views.get("label14").vw.setTop((int)((32d / 100 * height) - (views.get("label14").vw.getHeight())));
views.get("label14").vw.setLeft((int)((125d / 100 * height)));
views.get("button14").vw.setTop((int)((35d / 100 * height) - (views.get("button14").vw.getHeight())));
views.get("button14").vw.setLeft((int)((116d / 100 * height)));
views.get("imageview5").vw.setTop((int)((60d / 100 * height) - (views.get("imageview5").vw.getHeight())));
views.get("imageview5").vw.setLeft((int)((8d / 100 * height)));
views.get("label5").vw.setTop((int)((59d / 100 * height) - (views.get("label5").vw.getHeight())));
views.get("label5").vw.setLeft((int)((15d / 100 * height)));
views.get("button5").vw.setTop((int)((62d / 100 * height) - (views.get("button5").vw.getHeight())));
views.get("button5").vw.setLeft((int)((6d / 100 * height)));
views.get("imageview6").vw.setTop((int)((60d / 100 * height) - (views.get("imageview6").vw.getHeight())));
views.get("imageview6").vw.setLeft((int)((30d / 100 * height)));
views.get("label6").vw.setTop((int)((59d / 100 * height) - (views.get("label6").vw.getHeight())));
views.get("label6").vw.setLeft((int)((37d / 100 * height)));
views.get("button6").vw.setTop((int)((62d / 100 * height) - (views.get("button6").vw.getHeight())));
views.get("button6").vw.setLeft((int)((28d / 100 * height)));
views.get("imageview7").vw.setTop((int)((60d / 100 * height) - (views.get("imageview7").vw.getHeight())));
views.get("imageview7").vw.setLeft((int)((52d / 100 * height)));
views.get("label7").vw.setTop((int)((59d / 100 * height) - (views.get("label7").vw.getHeight())));
views.get("label7").vw.setLeft((int)((59d / 100 * height)));
views.get("button7").vw.setTop((int)((62d / 100 * height) - (views.get("button7").vw.getHeight())));
views.get("button7").vw.setLeft((int)((50d / 100 * height)));
views.get("imageview8").vw.setTop((int)((60d / 100 * height) - (views.get("imageview8").vw.getHeight())));
views.get("imageview8").vw.setLeft((int)((74d / 100 * height)));
views.get("label8").vw.setTop((int)((59d / 100 * height) - (views.get("label8").vw.getHeight())));
views.get("label8").vw.setLeft((int)((81d / 100 * height)));
views.get("button8").vw.setTop((int)((62d / 100 * height) - (views.get("button8").vw.getHeight())));
views.get("button8").vw.setLeft((int)((72d / 100 * height)));
views.get("imageview8").vw.setTop((int)((60d / 100 * height) - (views.get("imageview8").vw.getHeight())));
views.get("imageview8").vw.setLeft((int)((74d / 100 * height)));
views.get("label8").vw.setTop((int)((59d / 100 * height) - (views.get("label8").vw.getHeight())));
views.get("label8").vw.setLeft((int)((81d / 100 * height)));
views.get("button8").vw.setTop((int)((62d / 100 * height) - (views.get("button8").vw.getHeight())));
views.get("button8").vw.setLeft((int)((72d / 100 * height)));
views.get("imageview9").vw.setTop((int)((87d / 100 * height) - (views.get("imageview9").vw.getHeight())));
views.get("imageview9").vw.setLeft((int)((18d / 100 * height)));
views.get("label9").vw.setTop((int)((86d / 100 * height) - (views.get("label9").vw.getHeight())));
views.get("label9").vw.setLeft((int)((25d / 100 * height)));
views.get("button9").vw.setTop((int)((89d / 100 * height) - (views.get("button9").vw.getHeight())));
views.get("button9").vw.setLeft((int)((16d / 100 * height)));
views.get("imageview10").vw.setTop((int)((87d / 100 * height) - (views.get("imageview10").vw.getHeight())));
views.get("imageview10").vw.setLeft((int)((41d / 100 * height)));
views.get("label10").vw.setTop((int)((86d / 100 * height) - (views.get("label10").vw.getHeight())));
views.get("label10").vw.setLeft((int)((48d / 100 * height)));
views.get("button10").vw.setTop((int)((89d / 100 * height) - (views.get("button10").vw.getHeight())));
views.get("button10").vw.setLeft((int)((39d / 100 * height)));
views.get("imageview11").vw.setTop((int)((87d / 100 * height) - (views.get("imageview11").vw.getHeight())));
views.get("imageview11").vw.setLeft((int)((64d / 100 * height)));
views.get("label11").vw.setTop((int)((86d / 100 * height) - (views.get("label11").vw.getHeight())));
views.get("label11").vw.setLeft((int)((71d / 100 * height)));
views.get("button11").vw.setTop((int)((89d / 100 * height) - (views.get("button11").vw.getHeight())));
views.get("button11").vw.setLeft((int)((62d / 100 * height)));
views.get("imageview12").vw.setTop((int)((87d / 100 * height) - (views.get("imageview12").vw.getHeight())));
views.get("imageview12").vw.setLeft((int)((87d / 100 * height)));
views.get("label12").vw.setTop((int)((86d / 100 * height) - (views.get("label12").vw.getHeight())));
views.get("label12").vw.setLeft((int)((94d / 100 * height)));
views.get("button12").vw.setTop((int)((89d / 100 * height) - (views.get("button12").vw.getHeight())));
views.get("button12").vw.setLeft((int)((85d / 100 * height)));
views.get("imageview12").vw.setTop((int)((87d / 100 * height) - (views.get("imageview12").vw.getHeight())));
views.get("imageview12").vw.setLeft((int)((87d / 100 * height)));
views.get("label12").vw.setTop((int)((86d / 100 * height) - (views.get("label12").vw.getHeight())));
views.get("label12").vw.setLeft((int)((94d / 100 * height)));
views.get("button12").vw.setTop((int)((89d / 100 * height) - (views.get("button12").vw.getHeight())));
views.get("button12").vw.setLeft((int)((85d / 100 * height)));
views.get("button21").vw.setTop((int)((102d / 100 * height) - (views.get("button21").vw.getHeight())));
views.get("button21").vw.setLeft((int)((75d / 100 * height)));
views.get("button21").vw.setWidth((int)((30d / 100 * height)));
views.get("button21").vw.setHeight((int)((15d / 100 * height)));

}
}