package b4a.example.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_number_writing{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3d);
views.get("button1").vw.setTop((int)((15d / 100 * height) - (views.get("button1").vw.getHeight())));
views.get("button1").vw.setLeft((int)((5d / 100 * height)));
views.get("fv1").vw.setTop((int)((48d / 100 * height) - (views.get("fv1").vw.getHeight())));
views.get("fv1").vw.setLeft((int)((115d / 100 * height)));
views.get("fv1").vw.setWidth((int)((50d / 100 * height)));
views.get("fv1").vw.setHeight((int)((60d / 100 * height)));
views.get("btn_clear").vw.setTop((int)((35d / 100 * height) - (views.get("btn_clear").vw.getHeight())));
views.get("btn_clear").vw.setLeft((int)((100d / 100 * height)));
views.get("b3").vw.setTop((int)((27d / 100 * height) - (views.get("b3").vw.getHeight())));
views.get("b3").vw.setLeft((int)((15d / 100 * height)));
views.get("b3").vw.setWidth((int)((20d / 100 * height)));
views.get("b3").vw.setHeight((int)((20d / 100 * height)));
views.get("btnb").vw.setTop((int)((27d / 100 * height) - (views.get("btnb").vw.getHeight())));
views.get("btnb").vw.setLeft((int)((28d / 100 * height)));
views.get("btnb").vw.setWidth((int)((20d / 100 * height)));
views.get("btnb").vw.setHeight((int)((20d / 100 * height)));
views.get("btnc").vw.setTop((int)((27d / 100 * height) - (views.get("btnc").vw.getHeight())));
views.get("btnc").vw.setLeft((int)((41d / 100 * height)));
views.get("btnc").vw.setWidth((int)((20d / 100 * height)));
views.get("btnc").vw.setHeight((int)((20d / 100 * height)));
views.get("btnd").vw.setTop((int)((27d / 100 * height) - (views.get("btnd").vw.getHeight())));
views.get("btnd").vw.setLeft((int)((54d / 100 * height)));
views.get("btnd").vw.setWidth((int)((20d / 100 * height)));
views.get("btnd").vw.setHeight((int)((20d / 100 * height)));
views.get("btne").vw.setTop((int)((27d / 100 * height) - (views.get("btne").vw.getHeight())));
views.get("btne").vw.setLeft((int)((70d / 100 * height)));
views.get("btne").vw.setWidth((int)((20d / 100 * height)));
views.get("btne").vw.setHeight((int)((20d / 100 * height)));
views.get("btnf").vw.setTop((int)((45d / 100 * height) - (views.get("btnf").vw.getHeight())));
views.get("btnf").vw.setLeft((int)((73d / 100 * height)));
views.get("btnf").vw.setWidth((int)((20d / 100 * height)));
views.get("btnf").vw.setHeight((int)((25d / 100 * height)));
views.get("btng").vw.setTop((int)((50d / 100 * height) - (views.get("btng").vw.getHeight())));
views.get("btng").vw.setLeft((int)((15d / 100 * height)));
views.get("btng").vw.setWidth((int)((20d / 100 * height)));
views.get("btng").vw.setHeight((int)((20d / 100 * height)));
views.get("btnh").vw.setTop((int)((50d / 100 * height) - (views.get("btnh").vw.getHeight())));
views.get("btnh").vw.setLeft((int)((28d / 100 * height)));
views.get("btnh").vw.setWidth((int)((20d / 100 * height)));
views.get("btnh").vw.setHeight((int)((20d / 100 * height)));
views.get("btni").vw.setTop((int)((50d / 100 * height) - (views.get("btni").vw.getHeight())));
views.get("btni").vw.setLeft((int)((41d / 100 * height)));
views.get("btni").vw.setWidth((int)((20d / 100 * height)));
views.get("btni").vw.setHeight((int)((20d / 100 * height)));
views.get("btnj").vw.setTop((int)((50d / 100 * height) - (views.get("btnj").vw.getHeight())));
views.get("btnj").vw.setLeft((int)((54d / 100 * height)));
views.get("btnj").vw.setWidth((int)((20d / 100 * height)));
views.get("btnj").vw.setHeight((int)((20d / 100 * height)));
views.get("i10").vw.setTop((int)((55d / 100 * height) - (views.get("i10").vw.getHeight())));
views.get("i10").vw.setLeft((int)((115d / 100 * height)));
views.get("i10").vw.setWidth((int)((50d / 100 * height)));
views.get("i10").vw.setHeight((int)((50d / 100 * height)));
views.get("i9").vw.setTop((int)((55d / 100 * height) - (views.get("i9").vw.getHeight())));
views.get("i9").vw.setLeft((int)((115d / 100 * height)));
views.get("i9").vw.setWidth((int)((50d / 100 * height)));
views.get("i9").vw.setHeight((int)((50d / 100 * height)));
views.get("i8").vw.setTop((int)((55d / 100 * height) - (views.get("i8").vw.getHeight())));
views.get("i8").vw.setLeft((int)((115d / 100 * height)));
views.get("i8").vw.setWidth((int)((50d / 100 * height)));
views.get("i8").vw.setHeight((int)((50d / 100 * height)));
views.get("i7").vw.setTop((int)((55d / 100 * height) - (views.get("i7").vw.getHeight())));
views.get("i7").vw.setLeft((int)((115d / 100 * height)));
views.get("i7").vw.setWidth((int)((50d / 100 * height)));
views.get("i7").vw.setHeight((int)((50d / 100 * height)));
views.get("i6").vw.setTop((int)((55d / 100 * height) - (views.get("i6").vw.getHeight())));
views.get("i6").vw.setLeft((int)((115d / 100 * height)));
views.get("i6").vw.setWidth((int)((50d / 100 * height)));
views.get("i6").vw.setHeight((int)((50d / 100 * height)));
views.get("i5").vw.setTop((int)((55d / 100 * height) - (views.get("i5").vw.getHeight())));
views.get("i5").vw.setLeft((int)((115d / 100 * height)));
views.get("i5").vw.setWidth((int)((50d / 100 * height)));
views.get("i5").vw.setHeight((int)((50d / 100 * height)));
views.get("i4").vw.setTop((int)((55d / 100 * height) - (views.get("i4").vw.getHeight())));
views.get("i4").vw.setLeft((int)((115d / 100 * height)));
views.get("i4").vw.setWidth((int)((50d / 100 * height)));
views.get("i4").vw.setHeight((int)((50d / 100 * height)));
views.get("i3").vw.setTop((int)((55d / 100 * height) - (views.get("i3").vw.getHeight())));
views.get("i3").vw.setLeft((int)((115d / 100 * height)));
views.get("i3").vw.setWidth((int)((50d / 100 * height)));
views.get("i3").vw.setHeight((int)((50d / 100 * height)));
views.get("i2").vw.setTop((int)((55d / 100 * height) - (views.get("i2").vw.getHeight())));
views.get("i2").vw.setLeft((int)((115d / 100 * height)));
views.get("i2").vw.setWidth((int)((50d / 100 * height)));
views.get("i2").vw.setHeight((int)((50d / 100 * height)));
views.get("i1").vw.setTop((int)((55d / 100 * height) - (views.get("i1").vw.getHeight())));
views.get("i1").vw.setLeft((int)((115d / 100 * height)));
views.get("i1").vw.setWidth((int)((50d / 100 * height)));
views.get("i1").vw.setHeight((int)((50d / 100 * height)));

}
}